function x = myStateTransitionFnc(x,u,dt)
    qw = u(3);
    qx = u(4);
    qy = u(5);
    qz = u(6);
    
    F =    [1 0  dt 0 ; ...
            0 1  0  dt; ...
            0 0  1  0 ; ...
            0 0  0  1];
            
    G =    [dt*dt/2    0    ; ...
              0      dt*dt/2; ...
              dt       0    ; ...
              0       dt   ]; ...

    x(1:4) = F*x(1:4) + G*u(1:2);
    
    ax = [ 0  -qx -qy -qz; ...
           qx  0   qz -qy; ...
           qy -qz  0   qx; ...
           qz  qy -qx  0];
    x(5:8) = (q(1) * eye(4) + ax)*x(5:8); 

end